dist: trusty
sudo: required
services:
  - docker
addons:
  apt:
    sources:
      - git-core
    packages:
      - git
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq docker-ce
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install global eslint eslint-config-aqua
language: node_js
node_js:
  - '8'
cache:
  yarn: true
script:
  - bash ./deploy/deploy.sh
