version: '3'
services:
  commando:
    image: "crawl/commando:latest"
    restart: always
    environment:
      - TOKEN=NDM5ODQ3ODUyNTM4MDY5MDAz.DeG8IQ.yu8gcWl9y6bvieXRTnNlZdZRAG4
      - COMMAND_PREFIX=b!
      - OWNERS=309081957604786176
      - DB=postgres://POSTGRES_USER_DEFINED_IN_POSTGRES_ENV:POSTGRES_PW_DEFINED_IN_POSTGRES_ENV@postgres:5432/POSTGRES_DB_EITHER_USER_DEFINED_IN_POSTGRES_ENV_OR_POSTGRES_DB_DEFINED_IN_POSTGRES
      - REDIS=redis
      - EXAMPLE_CHANNEL=bot-test
      - WEATHER_API=e0eb543585ddd668e6b41a75d0746be9
      - GOOGLE_API=AIzaSyCLD9unqAAv2eGMMube6tTxflh9Rud0Gp8
      - GOOGLE_CUSTOM_SEARCH=AIzaSyDaFNIfPMQt7pspNteOr0YZrET07kL2Zus
      - GOOGLE_CUSTOM_SEARCH_CX=https://cse.google.com/cse/publicurl?cx=007380827170742579153:meginozhd7s
      - SOUNDCLOUD_API=SOUNDCLOUD_API_KEY
      - SHERLOCK_API=SHERLOCK_API_KEY
      - PAGINATED_ITEMS=HOW_MANY_ITEMS_PER_PAGE_VIA_PAGINATION
      - DEFAULT_VOLUME=0.25
      - MAX_LENGTH=1000
      - MAX_SONGS=30
      - PASSES=UPD_PACKET_PASS
    volumes:
      - LOCALHOST_VOLUME_PATH/backgrounds:/assets/profile/backgrounds
    depends_on:
      - postgres
      - redis

  postgres:
    image: "postgres:9-alpine"
    environment:
      - POSTGRES_USER=commando
      - POSTGRES_PASSWORD=POSTGRES_PW
    volumes:
      - LOCALHOST_VOLUME_PATH/postgresql/data:/var/lib/postgresql/data

  redis:
    image: "redis:3-alpine"
    volumes:
      - LOCALHOST_VOLUME_PATH/redis/data:/data
